<a href="https://colab.research.google.com/github/zainali60/machine-learning-with-python-practice/blob/main/machine_Ch%3D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

vector_row = np.array([1, 2, 3])
vector_row

array([1, 2, 3])

In [2]:
row_col = np.array([[1],[2],[3]])
row_col

array([[1],
       [2],
       [3]])

In [3]:
matrix_object = np.mat([[1, 2],[1, 2],[1, 2]])
matrix_object


matrix([[1, 2],
        [1, 2],
        [1, 2]])

In [4]:
from scipy import sparse
mat = np.array([[1,2],[3,4],[5,6],[7,8]])
matrix_sparse = sparse.csr_matrix(mat)
matrix_sparse

<4x2 sparse matrix of type '<class 'numpy.longlong'>'
	with 8 stored elements in Compressed Sparse Row format>

In [5]:
type(matrix_sparse)

scipy.sparse.csr.csr_matrix

In [6]:
matrix_sparse.ndim

2

In [7]:
matrix_sparse.dtype

dtype('int64')

In [8]:
print(matrix_sparse)

  (0, 0)	1
  (0, 1)	2
  (1, 0)	3
  (1, 1)	4
  (2, 0)	5
  (2, 1)	6
  (3, 0)	7
  (3, 1)	8


In [9]:
matrix_large = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 5, 0, 0]])
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
matrix_large_sparse

<3x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 4 stored elements in Compressed Sparse Row format>

In [10]:
print(matrix_large_sparse)

  (0, 0)	1
  (1, 1)	1
  (2, 0)	3
  (2, 7)	5


In [11]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


In [12]:
matrix[1]

array([4, 5, 6])

In [13]:
matrix[1,1]

5

In [14]:
matrix[1:3,1]

array([5, 8])

In [15]:
matrix.shape

(3, 3)

In [16]:
matrix.size

9

In [17]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [18]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
add_100 = lambda i: i + 100
add_100

<function __main__.<lambda>>

In [20]:
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [21]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.max(matrix,axis=0)

array([7, 8, 9])

In [23]:
np.max(matrix,axis=1)

array([3, 6, 9])

In [24]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.mean(matrix)

5.0

In [26]:
np.var(matrix)

6.666666666666667

In [27]:
np.std(matrix)

2.581988897471611

In [28]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [29]:
np.mean(matrix, axis=1)

array([2., 5., 8.])

In [30]:
matrix.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [31]:
matrix.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
np.linalg.matrix_rank(matrix)

2

In [37]:
matrix.ndim

2

In [39]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.linalg.det(matrix)

0.0

In [41]:
matrix.diagonal()

array([1, 5, 9])

In [47]:
matrix.diagonal(offset=1)

array([2, 6])

In [48]:
matrix.trace()

15

In [49]:
sum(matrix.diagonal())

15

In [50]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)


In [51]:
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16])

In [52]:
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [55]:
np.dot(matrix,matrix)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [56]:
# dot product
matrix @ matrix

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [65]:
np.random.seed(4)

In [66]:
np.random.random(2)

array([0.96702984, 0.54723225])

In [68]:
np.random.randint(0,15,4)

array([ 2,  9, 10, 12])

In [73]:
np.random.randint(7)

4

In [74]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0,15,3)

array([-9.71560151,  8.97862761,  4.98375049])

In [75]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-4.70304988, -0.46174779, -3.07476976])

In [76]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.95665297, 1.43614665, 1.94897731])